# Site settings
title: Baby Shower
email: your-email@domain.com
url: https://example.github.io
description: "Join us in honoring parents-to-be Sarah & Brian"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#e2e5e7'
  links: '#fff'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: babylist
    url: https://www.babylist.com/sarah-nagle
    path: img/babylist.png
  - title: buy-buy-baby
    url: https://www.buybuybaby.com/store/giftregistry/viewregistryguest/549051794?eventType=Baby
    path: img/buybuybaby.svg

# Build settings
markdown: kramdown
permalink: pretty
